apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: understudy

# Include the base resources
resources:
  - ../../base

# Azure-specific patches
patches:
  - path: pvc-azure.yaml
  - path: postgres-azure.yaml
    target:
      kind: StatefulSet
      name: postgres
  - path: images-amd64.yaml

# Azure-specific labels
labels:
  - pairs:
      cloud-provider: azure
      deployment-type: aks