apiVersion: v1
kind: ConfigMap
metadata:
  name: understudy-config
  namespace: understudy
data:
  APP_NAME: "Understudy"
  VERSION: "1.0.0"
  API_V1_STR: "/api/v1"
  LOG_LEVEL: "INFO"
  CARBON_TRACKING_ENABLED: "true"
  DEFAULT_TRAINING_SIZES: "[10, 100, 1000]"
  DEFAULT_LEARNING_RATE: "0.0003"
  DEFAULT_NUM_EPOCHS: "3"
  DEFAULT_LORA_R: "8"
  DEFAULT_LORA_ALPHA: "16"
  DEFAULT_SIMILARITY_THRESHOLD: "0.85"
  DEFAULT_EVALUATION_SAMPLE_SIZE: "5"
  MAX_DEPLOYMENTS: "10"
  DEPLOYMENT_THRESHOLD: "0.85"
  EVALUATION_BATCH_SIZE: "5"
  RUNPOD_TRAINING_ENABLED: "true"
  RUNPOD_GPU_TYPE: "NVIDIA GeForce RTX 4090"
  RUNPOD_CONTAINER_IMAGE: "runpod/pytorch:2.0.1-py3.10-cuda11.8.0-devel-ubuntu22.04"
  RUNPOD_DISK_SIZE: "50"